name: Go

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23'

    - name: Environment Information
      run: go env
  
    - name: List Packages or Modules 
      run: go list ./source
        
    - name: Report Mistakes in Package  
      run: go vet ./source
        
    - name: Update Package to New APIs  
      run: go fix ./source
        
    - name: Format Package 
      run: go fmt ./source

    - name: Compile Package and Dependencies
      run: GOARCH=amd64 GOOS=linux go build -o ./binary/htdinet ./source/main.go
